"""Track student follow-up status

Revision ID: c744f7d9188a
Revises: 36e85dcc5d7e
Create Date: 2026-09-18 17:45:41.613009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c744f7d9188a'
down_revision = '36e85dcc5d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followed_up', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.alter_column('followed_up', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('followed_up')

    # ### end Alembic commands ###
